export default {
    COOKIE: "COOKIE",
    TOKEN: "TOKEN",
    AUTH_USER: "AUTH_USER",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CURRENT_USER: "CURRENT_USER",
    LIST_USERS: "LIST_USERS",
    NEW_USER: "NEW_USER",
    REGISTER: "REGISTER",
    VISITORS_FORM: "VISITORS_FORM",
    RESIDENT_FORM: "RESIDENT_FORM",
    INITIALIZE_APP: "INITIALIZE_APP",
    INITIALIZATION_FAILURE: "INITIALIZATION_FAILURE",
    INITIALIZE_PAYSTACK_TRANSACTION: "INITIALIZE_PAYSTACK_TRANSACTION",
    REQUEST: type => `${type}_REQUEST`,
    REQUEST_FAILURE: type => `${type}_REQUEST_FAILURE`,
    REQUEST_SUCCESS: type => `${type}_SUCCESS`
}